### ISSUE TITLE
Version too old 

### ISSUE THREAD

**Issue by ResponseTime** [471D38UNNUX/Ngrok-Installer#3]
![image](https://github.com/471D38UNNUX/Ngrok-Installer/assets/80978976/ea470a9d-318d-4e05-a415-bc61dbd78712)

**Comment by 471D38UNNUX** [comment]
Please do git clone again. I have been update this repository. That old ngrok issue should have been fixed too. Thanks for using my repository.

**Comment by ResponseTime** [comment]
> Please do git clone again. I have been update this repository. That old ngrok issue should have been fixed too. Thanks for using my repository.

Cool, thanks for still maintaining it.
